# Generated by Django 5.1.1 on 2025-03-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reviews',
            new_name='review',
        ),
    ]
