# Generated by Django 5.1.1 on 2025-03-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_role_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
