# Generated by Django 5.1.1 on 2025-03-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_user_is_admin_remove_user_is_moderator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
