# Generated by Django 5.1.1 on 2025-03-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(blank=True, help_text='6-значный код подтверждения', max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
