# Generated by Django 5.1.1 on 2025-03-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_user_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secret',
            new_name='confirmation_code',
        ),
    ]
